# Ignore some builtin hints
- ignore:
    name: "Reduce duplication"
    within:
      - Data.Aeson.Types.ToJSON
- ignore:
    name: "Eta reduce"
- ignore:
    name: "Use newtype instead of data"
    within:
      - Data.Aeson.Types.Internal

# CPP confuses
- ignore:
    name: "Use fewer imports"
    within:
      - Data.Aeson.Types.Internal
